language: node_js
sudo: required
node_js:
  - 4
before_script:
  - npm install -g yarn
# install: |
  # npm install -g npm@latest
  # npm install --registry http://registry.npmjs.org
# install: |
#   yarn install
script:
  - npm run unit
after_script:
  - npm run coveralls
# addons:
#   sauce_connect:
#     username: "Your Sauce Labs username"
#     access_key: "Your Sauce Labs access key"
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/vue-cli
  yarn: true
